export type EnemyAttack = "Melee" | "Dash" | "Projectile" | "Volley" | "Spike" | "Nova" | "Summon";
export type RegionId = "Verdant" | "Ember" | "Frost" | "Storm" | "Umbral";

export interface EnemyDefinition {
  readonly id: string;
  readonly name: string;
  readonly region: RegionId;
  readonly attack: EnemyAttack;
  readonly health: number;
  readonly damage: number;
  readonly speed: number;
  readonly range: number;
  readonly cooldown: number;
  readonly xp: number;
  readonly color: readonly [number, number, number];
  readonly accent: readonly [number, number, number];
  readonly scale: number;
  readonly boss?: true;
  readonly projectileCount?: number;
}

export const REGULAR_ENEMIES: readonly EnemyDefinition[] = [
  {
    id: "moss_brawler",
    name: "Moss Brawler",
    region: "Verdant",
    attack: "Melee",
    health: 85,
    damage: 11,
    speed: 10,
    range: 6,
    cooldown: 1.25,
    xp: 28,
    color: [62, 111, 68],
    accent: [151, 214, 94],
    scale: 1,
  },
  {
    id: "thorn_runner",
    name: "Thorn Runner",
    region: "Verdant",
    attack: "Dash",
    health: 65,
    damage: 13,
    speed: 18,
    range: 18,
    cooldown: 2.4,
    xp: 32,
    color: [44, 91, 57],
    accent: [205, 244, 112],
    scale: 0.85,
  },
  {
    id: "spore_slinger",
    name: "Spore Slinger",
    region: "Verdant",
    attack: "Projectile",
    health: 70,
    damage: 10,
    speed: 9,
    range: 55,
    cooldown: 1.8,
    xp: 34,
    color: [96, 72, 122],
    accent: [226, 132, 255],
    scale: 0.95,
  },
  {
    id: "root_shaman",
    name: "Root Shaman",
    region: "Verdant",
    attack: "Spike",
    health: 95,
    damage: 18,
    speed: 8,
    range: 50,
    cooldown: 3.2,
    xp: 42,
    color: [88, 67, 43],
    accent: [111, 226, 125],
    scale: 1.1,
  },
  {
    id: "cinder_guard",
    name: "Cinder Guard",
    region: "Ember",
    attack: "Melee",
    health: 125,
    damage: 17,
    speed: 9,
    range: 6,
    cooldown: 1.4,
    xp: 40,
    color: [104, 47, 35],
    accent: [255, 105, 44],
    scale: 1.15,
  },
  {
    id: "ash_stalker",
    name: "Ash Stalker",
    region: "Ember",
    attack: "Dash",
    health: 82,
    damage: 16,
    speed: 21,
    range: 20,
    cooldown: 2.1,
    xp: 43,
    color: [58, 50, 53],
    accent: [255, 128, 63],
    scale: 0.9,
  },
  {
    id: "magma_archer",
    name: "Magma Archer",
    region: "Ember",
    attack: "Volley",
    health: 80,
    damage: 9,
    speed: 9,
    range: 65,
    cooldown: 2.8,
    xp: 46,
    color: [91, 43, 37],
    accent: [255, 183, 58],
    scale: 1,
    projectileCount: 3,
  },
  {
    id: "lava_oracle",
    name: "Lava Oracle",
    region: "Ember",
    attack: "Nova",
    health: 105,
    damage: 20,
    speed: 7,
    range: 16,
    cooldown: 3.6,
    xp: 52,
    color: [72, 36, 54],
    accent: [255, 75, 34],
    scale: 1.05,
  },
  {
    id: "icebound_knight",
    name: "Icebound Knight",
    region: "Frost",
    attack: "Melee",
    health: 145,
    damage: 19,
    speed: 8,
    range: 6,
    cooldown: 1.5,
    xp: 48,
    color: [117, 163, 184],
    accent: [221, 250, 255],
    scale: 1.2,
  },
  {
    id: "glacier_hound",
    name: "Glacier Hound",
    region: "Frost",
    attack: "Dash",
    health: 88,
    damage: 17,
    speed: 23,
    range: 22,
    cooldown: 2,
    xp: 50,
    color: [74, 128, 161],
    accent: [156, 232, 255],
    scale: 0.8,
  },
  {
    id: "rime_bow",
    name: "Rime Bow",
    region: "Frost",
    attack: "Projectile",
    health: 92,
    damage: 15,
    speed: 8,
    range: 70,
    cooldown: 1.7,
    xp: 54,
    color: [91, 118, 149],
    accent: [189, 245, 255],
    scale: 1,
  },
  {
    id: "permafrost_seer",
    name: "Permafrost Seer",
    region: "Frost",
    attack: "Spike",
    health: 115,
    damage: 23,
    speed: 7,
    range: 60,
    cooldown: 3,
    xp: 60,
    color: [88, 96, 144],
    accent: [134, 217, 255],
    scale: 1.1,
  },
  {
    id: "gale_duelist",
    name: "Gale Duelist",
    region: "Storm",
    attack: "Dash",
    health: 110,
    damage: 20,
    speed: 24,
    range: 24,
    cooldown: 1.9,
    xp: 58,
    color: [66, 92, 129],
    accent: [103, 235, 255],
    scale: 0.95,
  },
  {
    id: "storm_lancer",
    name: "Storm Lancer",
    region: "Storm",
    attack: "Melee",
    health: 155,
    damage: 22,
    speed: 12,
    range: 8,
    cooldown: 1.25,
    xp: 62,
    color: [62, 74, 119],
    accent: [114, 171, 255],
    scale: 1.2,
  },
  {
    id: "tempest_marksman",
    name: "Tempest Marksman",
    region: "Storm",
    attack: "Volley",
    health: 105,
    damage: 12,
    speed: 11,
    range: 78,
    cooldown: 2.5,
    xp: 66,
    color: [52, 67, 105],
    accent: [160, 239, 255],
    scale: 1,
    projectileCount: 5,
  },
  {
    id: "thunder_caller",
    name: "Thunder Caller",
    region: "Storm",
    attack: "Spike",
    health: 135,
    damage: 27,
    speed: 9,
    range: 68,
    cooldown: 2.8,
    xp: 72,
    color: [67, 53, 112],
    accent: [217, 190, 255],
    scale: 1.1,
  },
  {
    id: "dusk_reaver",
    name: "Dusk Reaver",
    region: "Umbral",
    attack: "Melee",
    health: 175,
    damage: 25,
    speed: 13,
    range: 7,
    cooldown: 1.1,
    xp: 72,
    color: [48, 38, 66],
    accent: [209, 76, 191],
    scale: 1.2,
  },
  {
    id: "void_skitter",
    name: "Void Skitter",
    region: "Umbral",
    attack: "Dash",
    health: 105,
    damage: 24,
    speed: 27,
    range: 26,
    cooldown: 1.7,
    xp: 76,
    color: [36, 31, 53],
    accent: [229, 94, 255],
    scale: 0.8,
  },
  {
    id: "nightweaver",
    name: "Nightweaver",
    region: "Umbral",
    attack: "Summon",
    health: 135,
    damage: 15,
    speed: 9,
    range: 75,
    cooldown: 3.4,
    xp: 82,
    color: [62, 39, 82],
    accent: [246, 93, 210],
    scale: 1.05,
    projectileCount: 4,
  },
  {
    id: "abyss_channeler",
    name: "Abyss Channeler",
    region: "Umbral",
    attack: "Nova",
    health: 160,
    damage: 30,
    speed: 7,
    range: 19,
    cooldown: 3.2,
    xp: 88,
    color: [42, 31, 64],
    accent: [165, 74, 255],
    scale: 1.15,
  },
];

export const BOSSES: readonly EnemyDefinition[] = [
  {
    id: "elder_briar",
    name: "Elder Briar, the Overgrown",
    region: "Verdant",
    attack: "Summon",
    health: 650,
    damage: 20,
    speed: 8,
    range: 72,
    cooldown: 2.8,
    xp: 260,
    color: [45, 83, 50],
    accent: [180, 255, 98],
    scale: 2.2,
    boss: true,
    projectileCount: 6,
  },
  {
    id: "pyre_tyrant",
    name: "The Pyre Tyrant",
    region: "Ember",
    attack: "Nova",
    health: 800,
    damage: 32,
    speed: 9,
    range: 24,
    cooldown: 2.6,
    xp: 320,
    color: [87, 31, 26],
    accent: [255, 92, 25],
    scale: 2.35,
    boss: true,
  },
  {
    id: "frost_colossus",
    name: "Frostveil Colossus",
    region: "Frost",
    attack: "Spike",
    health: 950,
    damage: 36,
    speed: 7,
    range: 85,
    cooldown: 2.4,
    xp: 380,
    color: [91, 139, 165],
    accent: [212, 251, 255],
    scale: 2.6,
    boss: true,
  },
  {
    id: "skybreaker",
    name: "Skybreaker Matriarch",
    region: "Storm",
    attack: "Volley",
    health: 900,
    damage: 17,
    speed: 13,
    range: 95,
    cooldown: 2.1,
    xp: 410,
    color: [52, 63, 111],
    accent: [126, 231, 255],
    scale: 2.4,
    boss: true,
    projectileCount: 8,
  },
  {
    id: "null_sovereign",
    name: "The Null Sovereign",
    region: "Umbral",
    attack: "Summon",
    health: 1200,
    damage: 27,
    speed: 11,
    range: 90,
    cooldown: 2.2,
    xp: 500,
    color: [31, 24, 49],
    accent: [235, 65, 209],
    scale: 2.7,
    boss: true,
    projectileCount: 10,
  },
];

export const ALL_ENEMIES: readonly EnemyDefinition[] = [...REGULAR_ENEMIES, ...BOSSES];
